In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv("demo_esm2_t6_8M_UR50D.csv")
df_data.head()

,p_0,p_1,p_2,p_3,p_4,p_5,p_6,p_7,p_8,p_9,...,p_311,p_312,p_313,p_314,p_315,p_316,p_317,p_318,p_319,sequence
0,0.023940,-0.150466,0.179482,0.171875,-0.029212,-0.218203,-0.168054,-0.103375,-0.209554,-0.046833,...,-0.022504,0.047969,0.092184,0.013225,0.077896,-0.048180,0.026367,0.241542,0.041240,RDRQVKEAVHMSCVLMEYKGAFVVPHFGWGKTWVTSNM
1,0.029336,-0.190898,0.209369,0.201112,-0.044392,-0.224422,-0.176874,-0.103561,-0.216987,-0.139309,...,-0.135503,0.230788,0.191828,-0.007644,0.204875,-0.031691,-0.045532,0.324648,0.045703,YTRMTNHDFFGFLMKTPVFHQCSFVHEYCD
2,0.075828,-0.229619,0.132263,0.099707,-0.091811,-0.137896,-0.210758,-0.097438,-0.162082,-0.090033,...,-0.142386,0.158240,0.150357,-0.029255,0.124520,-0.112364,-0.019336,0.194240,0.055506,DTAFLEQLKWYDSTNCAMCFSVVTSIHLCPTGFKQHKQ
3,0.115553,-0.047585,0.192272,0.293189,-0.084745,-0.393975,-0.225736,-0.213541,-0.246759,-0.176075,...,-0.028565,-0.141988,0.167204,0.068105,0.238733,-0.038086,-0.118758,0.263298,0.056556,SWEKMPHECVMVNAMMHWKRCLMTGMYEGVKT
4,0.126345,-0.179531,0.239836,0.061843,0.052397,-0.161007,-0.189167,-0.093058,-0.184163,-0.138902,...,-0.047598,0.201968,0.025940,-0.032571,0.095961,-0.020732,0.160132,0.134403,-0.073969,GVSHVESHTWPANIGESA

In [3]:
import numpy as np

In [4]:
np.save("embeddings.npy", df_data.drop(columns=["sequence"]).values)

In [5]:
df = pd.read_csv("biosieve_example_dataset_1000.csv")
df.head(5)

,id,sequence,label,group,cluster_id,source,species,structure_id,embedding_id,date,target
0,pep_0946,RDRQVKEAVHMSCVLMEYKGAFVVPHFGWGKTWVTSNM,0,study_B00,clust_041,internal_db,Homo_sapiens,PDB_7096,emb_0946,2022-01-03,0.303352
1,pep_0453,YTRMTNHDFFGFLMKTPVFHQCSFVHEYCD,0,study_D00,clust_074,internal_db,Mus_musculus,PDB_3277,emb_0453,2020-08-24,0.158055
2,pep_0305,DTAFLEQLKWYDSTNCAMCFSVVTSIHLCPTGFKQHKQ,1,study_Y00,clust_005,uniprot,Rattus_norvegicus,NaN,emb_0305,2022-12-16,0.536003
3,pep_0434,SWEKMPHECVMVNAMMHWKRCLMTGMYEGVKT,0,study_J00,clust_080,uniprot,Escherichia_coli,NaN,emb_0434,2025-11-25,0.192696
4,pep_0865,GVSHVESHTWPANIGESA,1,study_Z00,clust_046,synthetic,Mus_musculus,PDB_9636,emb_0865,2025-02-08,0.161054

In [6]:
ids = df["id"].astype(str).tolist()

In [7]:
pd.DataFrame({"id": ids}).to_csv("embedding_ids.csv", index=False)