In [1]:
import pandas as pd

In [2]:
df_data = pd.read_csv("biosieve_example_dataset_1000.csv")
df_data.head()

,id,sequence,label,group,cluster_id,source,species,structure_id,embedding_id,date,target
0,pep_0946,RDRQVKEAVHMSCVLMEYKGAFVVPHFGWGKTWVTSNM,0,study_B00,clust_041,internal_db,Homo_sapiens,PDB_7096,emb_0946,2022-01-03,0.303352
1,pep_0453,YTRMTNHDFFGFLMKTPVFHQCSFVHEYCD,0,study_D00,clust_074,internal_db,Mus_musculus,PDB_3277,emb_0453,2020-08-24,0.158055
2,pep_0305,DTAFLEQLKWYDSTNCAMCFSVVTSIHLCPTGFKQHKQ,1,study_Y00,clust_005,uniprot,Rattus_norvegicus,NaN,emb_0305,2022-12-16,0.536003
3,pep_0434,SWEKMPHECVMVNAMMHWKRCLMTGMYEGVKT,0,study_J00,clust_080,uniprot,Escherichia_coli,NaN,emb_0434,2025-11-25,0.192696
4,pep_0865,GVSHVESHTWPANIGESA,1,study_Z00,clust_046,synthetic,Mus_musculus,PDB_9636,emb_0865,2025-02-08,0.161054

In [3]:
df_map = df_data[["id", "cluster_id"]]
df_map.head()

         id cluster_id
0  pep_0946  clust_041
1  pep_0453  clust_074
2  pep_0305  clust_005
3  pep_0434  clust_080
4  pep_0865  clust_046

In [4]:
df_map.to_csv("cluster_map.csv", index=False)